[module]
  [module.hugoVersion]
  min = "0.146.0"

[[module.mounts]]
source = 'layouts'
target = 'layouts'
[[module.mounts]]
source = 'assets/js/vendor/finkregh/ical'
target = 'assets/js/vendor/finkregh/ical'
