#!/usr/bin/env python3
"""iCalendar Validation Script for Hugo iCalendar Templates.

This script validates the generated .ics files to ensure they:
1. Are valid iCalendar format
2. Contain expected properties
3. Have correct recurrence rules
4. Match the source markdown content

Usage:
    python validate_ics.py <base_path>

Where <base_path> is the root directory containing the Hugo site structure.
For theme component: hugo-theme-component-ical/.github/exampleSite
For demo site: demo
"""

# ruff: noqa: T201, ANN401, E501

import argparse
from collections.abc import Generator
import logging
import re
import sys
import time
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import structlog
import yaml
from dateutil.rrule import rrulestr
from icalendar import Calendar, Component

# Configure structlog
structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.processors.JSONRenderer(),
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

log = structlog.get_logger()

# Constants
MIN_PATH_PARTS = 2
CALENDAR_FILENAME = "calendar.ics"


@contextmanager
def performance_timer(operation_name: str) -> Generator[None, Any, None]:
    """Context manager for timing operations."""
    start_time = time.time()
    try:
        yield
    finally:
        end_time = time.time()
        duration = end_time - start_time
        print(f"⏱️  {operation_name}: {duration:.3f}s")


class ICalValidator:
    """Validator for iCalendar files generated by Hugo templates."""

    def __init__(self) -> None:
        """Initialize the validator with empty error and warning lists."""
        self.errors: list[str] = []
        self.warnings: list[str] = []
        self.validated_files: int = 0
        self.whitespace_violations: int = 0
        self.empty_lines_found: int = 0
        self.trailing_whitespace_found: int = 0
        self.invalid_folding_found: int = 0

    def log_error(self, message: str, **kwargs: Any) -> None:
        """Log an error message."""
        # Include file name in the error message if available
        ics_file = kwargs.get("ics_file", "")
        formatted_message = f"{message} (file: {ics_file})" if ics_file else message
        self.errors.append(formatted_message)
        log.error(message, **kwargs)

    def log_warning(self, message: str, **kwargs: Any) -> None:
        """Log a warning message."""
        # Include file name in the warning message if available
        ics_file = kwargs.get("ics_file", "")
        formatted_message = f"{message} (file: {ics_file})" if ics_file else message
        self.warnings.append(formatted_message)
        log.warning(message, **kwargs)

    def log_info(self, message: str, **kwargs: Any) -> None:
        """Log an info message."""
        log.info(message, **kwargs)

    def parse_markdown_frontmatter(self, md_file: str) -> dict[str, Any]:
        """Parse the YAML frontmatter from a markdown file."""
        try:
            content = Path(md_file).read_text(encoding="utf-8")

            # Extract frontmatter between --- markers
            if content.startswith("---\n"):
                end_marker = content.find("\n---\n", 4)
                if end_marker != -1:
                    frontmatter = content[4:end_marker]
                    return yaml.safe_load(frontmatter) or {}
            else:
                return {}
        except (OSError, yaml.YAMLError) as e:
            self.log_error(
                "Failed to parse frontmatter from file",
                md_file=md_file,
                error=str(e),
            )
        return {}

    def validate_ical_structure(
        self,
        cal: Component,
        ics_file: str,
    ) -> Component | None:
        """Validate basic iCalendar structure."""
        self.log_info("Validating structure", ics_file=ics_file)

        # Check for required calendar properties
        if not cal.get("VERSION"):
            self.log_error("Missing VERSION property", ics_file=ics_file)

        if not cal.get("PRODID"):
            self.log_error("Missing PRODID property", ics_file=ics_file)

        # Check for events
        events = [component for component in cal.walk() if component.name == "VEVENT"]
        if not events:
            self.log_error("No VEVENT components found", ics_file=ics_file)
            return None

        return events[0]  # Return first event for further validation

    def validate_event_properties(
        self,
        event: Component,
        frontmatter: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate event properties against frontmatter."""
        self.log_info("Validating event properties", ics_file=ics_file)

        # Check SUMMARY (title)
        if "title" in frontmatter:
            summary = event.get("SUMMARY")
            if summary:
                if str(summary) != frontmatter["title"]:
                    self.log_error(
                        "SUMMARY doesn't match title",
                        ics_file=ics_file,
                        summary=str(summary),
                        expected_title=frontmatter["title"],
                    )
            else:
                self.log_error("Missing SUMMARY property", ics_file=ics_file)

        # Check DTSTART
        if "startDate" in frontmatter:
            dtstart = event.get("DTSTART")
            if not dtstart:
                self.log_error("Missing DTSTART property", ics_file=ics_file)

        # Check DTEND
        if "endDate" in frontmatter:
            dtend = event.get("DTEND")
            if not dtend:
                self.log_error("Missing DTEND property", ics_file=ics_file)

        # Check UID
        uid = event.get("UID")
        if not uid:
            self.log_error("Missing UID property", ics_file=ics_file)

        # Check DTSTAMP
        dtstamp = event.get("DTSTAMP")
        if not dtstamp:
            self.log_error("Missing DTSTAMP property", ics_file=ics_file)

    def _validate_freq(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate FREQ parameter."""
        if "freq" in expected_rule:
            actual_freq = rrule.get("FREQ")
            expected_freq = [expected_rule["freq"]]
            if actual_freq != expected_freq:
                self.log_error(
                    "FREQ mismatch",
                    ics_file=ics_file,
                    expected=expected_rule["freq"],
                    actual=actual_freq,
                )

    def _validate_bymonth(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate BYMONTH parameter."""
        if "byMonth" in expected_rule:
            expected_month = [expected_rule["byMonth"]]
            actual_month = rrule.get("BYMONTH")
            if actual_month != expected_month:
                self.log_error(
                    "BYMONTH mismatch",
                    ics_file=ics_file,
                    expected=expected_month,
                    actual=actual_month,
                )

    def _validate_byday(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate BYDAY parameter, handling ordinal format conversion."""
        if "byDay" in expected_rule:
            expected_day = expected_rule["byDay"]
            expected_setpos = expected_rule.get("bySetPos")

            # Normalize to list for comparison
            if not isinstance(expected_day, list):
                expected_day = [expected_day]

            actual_day = rrule.get("BYDAY")

            # Check if we should expect ordinal BYDAY format (BYDAY+BYSETPOS conversion)
            if expected_setpos is not None and len(expected_day) == 1:
                # Single day with setpos should be converted to ordinal format
                if not isinstance(expected_setpos, list):
                    expected_setpos = [expected_setpos]

                if len(expected_setpos) == 1:
                    # Should be converted to ordinal format like "3TH"
                    expected_ordinal = [f"{expected_setpos[0]}{expected_day[0]}"]
                    if actual_day != expected_ordinal:
                        self.log_error(
                            "BYDAY ordinal format mismatch (converted from BYDAY+BYSETPOS)",
                            ics_file=ics_file,
                            expected=expected_ordinal,
                            actual=actual_day,
                            original_byday=expected_day,
                            original_bysetpos=expected_setpos,
                        )
                    return

            # Standard BYDAY validation (no conversion)
            if actual_day != expected_day:
                self.log_error(
                    "BYDAY mismatch",
                    ics_file=ics_file,
                    expected=expected_day,
                    actual=actual_day,
                )

    def _validate_bysetpos(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate BYSETPOS parameter, handling conversion to ordinal BYDAY."""
        if "bySetPos" in expected_rule:
            expected_setpos = expected_rule["bySetPos"]
            expected_day = expected_rule.get("byDay")

            if isinstance(expected_setpos, list):
                expected_setpos_list = expected_setpos
            else:
                expected_setpos_list = [expected_setpos]

            actual_setpos = rrule.get("BYSETPOS")

            # Check if BYSETPOS should be converted to ordinal BYDAY format
            if expected_day is not None:
                # Normalize expected_day to list
                if not isinstance(expected_day, list):
                    expected_day = [expected_day]

                # If single day and single setpos, should be converted to ordinal format
                if len(expected_day) == 1 and len(expected_setpos_list) == 1:
                    # BYSETPOS should be absent (converted to ordinal BYDAY)
                    if actual_setpos is not None:
                        self.log_error(
                            "BYSETPOS should be absent (converted to ordinal BYDAY format)",
                            ics_file=ics_file,
                            expected=None,
                            actual=actual_setpos,
                            converted_to_ordinal=f"{expected_setpos_list[0]}{expected_day[0]}",
                        )
                    return

            # Standard BYSETPOS validation (no conversion)
            if actual_setpos != expected_setpos_list:
                self.log_error(
                    "BYSETPOS mismatch",
                    ics_file=ics_file,
                    expected=expected_setpos_list,
                    actual=actual_setpos,
                )

    def _validate_interval(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate INTERVAL parameter - now always required (RFC 5545 compliance)."""
        # INTERVAL should always be present, default to 1 if not specified in frontmatter
        expected_interval_value = expected_rule.get("interval", 1)
        expected_interval = [expected_interval_value]

        actual_interval = rrule.get("INTERVAL")
        if actual_interval != expected_interval:
            self.log_error(
                "INTERVAL mismatch (INTERVAL is now always required)",
                ics_file=ics_file,
                expected=expected_interval,
                actual=actual_interval,
            )

    def _validate_count(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate COUNT parameter."""
        if "count" in expected_rule:
            expected_count = [expected_rule["count"]]
            actual_count = rrule.get("COUNT")
            if actual_count != expected_count:
                self.log_error(
                    "COUNT mismatch",
                    ics_file=ics_file,
                    expected=expected_count,
                    actual=actual_count,
                )
            else:
                # Informational output
                print(
                    f"ℹ️  Event will occur {expected_rule['count']} times (COUNT={expected_rule['count']})",
                )

    def _validate_until(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate UNTIL parameter."""
        if "until" in expected_rule:
            actual_until = rrule.get("UNTIL")
            if actual_until is None:
                self.log_error(
                    "UNTIL missing",
                    ics_file=ics_file,
                    expected=expected_rule["until"],
                    actual=None,
                )
            else:
                # Parse expected UNTIL date from frontmatter
                expected_until_str = expected_rule["until"]

                # Get actual UNTIL value - it's a list with one datetime
                actual_until_dt = (
                    actual_until[0] if isinstance(actual_until, list) else actual_until
                )

                # Convert to string for comparison (YYYYMMDD format or YYYYMMDDTHHMMSSZ)
                if hasattr(actual_until_dt, "strftime"):
                    # Format as iCalendar date/datetime
                    if hasattr(actual_until_dt, "hour"):
                        actual_until_str = actual_until_dt.strftime("%Y%m%dT%H%M%SZ")
                    else:
                        actual_until_str = actual_until_dt.strftime("%Y%m%d")
                else:
                    actual_until_str = str(actual_until_dt)

                # Compare - expected format from frontmatter should match
                # Normalize both for comparison (remove hyphens/colons)
                expected_normalized = (
                    expected_until_str.replace("-", "")
                    .replace(":", "")
                    .replace("T", "T")
                    .replace("Z", "Z")
                )
                actual_normalized = actual_until_str.replace("-", "").replace(":", "")

                if expected_normalized != actual_normalized:
                    self.log_error(
                        "UNTIL mismatch",
                        ics_file=ics_file,
                        expected=expected_until_str,
                        actual=actual_until_str,
                    )
                # Informational output - show human-readable date
                elif hasattr(actual_until_dt, "strftime"):
                    readable_date = actual_until_dt.strftime("%Y-%m-%d")
                    print(
                        f"ℹ️  Event will occur until {readable_date} (UNTIL={expected_until_str})",
                    )
                else:
                    print(
                        f"ℹ️  Event will occur until {expected_until_str} (UNTIL={expected_until_str})",
                    )

    def _validate_count_until_mutual_exclusivity(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate that COUNT and UNTIL are mutually exclusive (RFC 5545 requirement)."""
        has_count = "count" in expected_rule
        has_until = "until" in expected_rule

        if has_count and has_until:
            self.log_warning(
                "COUNT and UNTIL both present in frontmatter (RFC 5545 violation - they are mutually exclusive)",
                ics_file=ics_file,
            )

        # Check actual RRULE
        actual_count = rrule.get("COUNT")
        actual_until = rrule.get("UNTIL")

        if actual_count is not None and actual_until is not None:
            self.log_error(
                "COUNT and UNTIL both present in RRULE (RFC 5545 violation - they are mutually exclusive)",
                ics_file=ics_file,
                count=actual_count,
                until=actual_until,
            )

    def validate_rrule_component_order(self, rrule_str: str, ics_file: str) -> None:
        """Validate RRULE component ordering per RFC 5545."""
        # RFC 5545 specifies component order:
        # FREQ, UNTIL/COUNT, INTERVAL, BYSECOND, BYMINUTE, BYHOUR,
        # BYDAY, BYMONTHDAY, BYYEARDAY, BYWEEKNO, BYMONTH, BYSETPOS, WKST

        expected_order = [
            "FREQ",
            "UNTIL",
            "COUNT",
            "INTERVAL",
            "BYSECOND",
            "BYMINUTE",
            "BYHOUR",
            "BYDAY",
            "BYMONTHDAY",
            "BYYEARDAY",
            "BYWEEKNO",
            "BYMONTH",
            "BYSETPOS",
            "WKST",
        ]

        # Parse RRULE components
        components = []
        for part in rrule_str.split(";"):
            if "=" in part:
                component = part.split("=")[0].strip()
                components.append(component)

        # Check ordering
        last_index = -1
        for component in components:
            if component in expected_order:
                current_index = expected_order.index(component)
                if current_index < last_index:
                    self.log_warning(
                        f"RRULE component order violation: {component} should come before previous components",
                        ics_file=ics_file,
                        rrule=rrule_str,
                    )
                last_index = current_index

    def validate_rrule_edge_cases(
        self,
        rrule: Component,
        expected_rule: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate edge cases and boundary conditions."""
        # Validate ordinal BYDAY ranges
        if "byDay" in expected_rule:
            byday_values = rrule.get("BYDAY", [])
            for byday in byday_values:
                if isinstance(byday, str) and len(byday) > 2:
                    # Extract ordinal prefix
                    ordinal_match = re.match(r"^(-?\d+)([A-Z]{2})$", byday)
                    if ordinal_match:
                        ordinal = int(ordinal_match.group(1))
                        if ordinal < -5 or ordinal > 5 or ordinal == 0:
                            self.log_error(
                                f"Invalid BYDAY ordinal: {ordinal}. Must be -5 to -1 or 1 to 5",
                                ics_file=ics_file,
                                byday=byday,
                            )

        # Validate BYSETPOS usage
        if "bySetPos" in expected_rule and "byDay" in expected_rule:
            expected_day = expected_rule["byDay"]
            expected_setpos = expected_rule["bySetPos"]

            # Check if this should have been converted to ordinal format
            if (
                isinstance(expected_day, str)
                and not re.match(r"^-?\d+[A-Z]{2}$", expected_day)
                and isinstance(expected_setpos, (int, str))
                and str(expected_setpos).lstrip("-").isdigit()
            ):

                actual_setpos = rrule.get("BYSETPOS")
                if actual_setpos is not None:
                    self.log_warning(
                        "BYSETPOS present but could be converted to ordinal BYDAY format",
                        ics_file=ics_file,
                        suggestion=f"{expected_setpos}{expected_day}",
                    )

    def show_recurrence_entries(self, event: Component, ics_file: str) -> None:
        """Show the first 4 entries from recurrence rules."""
        rrule = event.get("RRULE")
        if not rrule:
            return

        dtstart = event.get("DTSTART")
        if not dtstart:
            return

        try:
            # Enhanced RRULE string conversion to fix warnings
            if hasattr(rrule, "to_ical"):
                # Use the iCalendar library's native conversion
                rrule_str = rrule.to_ical().decode("utf-8")
                rrule_str = rrule_str.removeprefix("RRULE:")  # Remove 'RRULE:' prefix
            else:
                # Fallback to string conversion
                rrule_str = str(rrule)
                rrule_str = rrule_str.removeprefix("RRULE:")

            start_dt = dtstart.dt

            # Enhanced timezone handling
            if hasattr(start_dt, "tzinfo"):
                if start_dt.tzinfo is None:
                    # Handle naive datetime
                    start_dt = start_dt.replace(tzinfo=None)
                else:
                    # Convert to UTC for consistent processing
                    start_dt = start_dt.astimezone(timezone.utc).replace(tzinfo=None)

            # Generate first 4 occurrences with better error handling
            try:
                rule = rrulestr(rrule_str, dtstart=start_dt)
                occurrences = list(rule[:4])

                print(f"\n📅 First 4 recurrence entries for {ics_file}:")
                for i, occurrence in enumerate(occurrences, 1):
                    print(f"  {i}. {occurrence.strftime('%Y-%m-%d %H:%M:%S')}")
            except ValueError as ve:
                # More specific error handling for RRULE parsing
                self.log_warning(
                    f"RRULE parsing failed: {ve}. RRULE: {rrule_str}",
                    ics_file=ics_file,
                )
            except Exception as e:
                # Generic fallback
                self.log_warning(
                    f"Could not generate recurrence entries: {e}",
                    ics_file=ics_file,
                )

        except Exception as e:  # noqa: BLE001
            self.log_warning(
                f"Error processing recurrence rule: {e}",
                ics_file=ics_file,
            )

    def validate_valarm_components(
        self,
        event: Component,
        frontmatter: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate VALARM components against frontmatter."""
        # Determine if this is a calendar-alarms.ics file or regular calendar.ics
        is_alarms_file = "calendar-alarms.ics" in ics_file

        # Find VALARM components
        valarms = [
            component for component in event.walk() if component.name == "VALARM"
        ]

        if "alarms" not in frontmatter:
            # No alarms defined in frontmatter
            if valarms:
                self.log_error(
                    "Unexpected VALARM components found",
                    ics_file=ics_file,
                    actual=len(valarms),
                )
            return

        self.log_info("Validating VALARM components", ics_file=ics_file)
        expected_alarms = frontmatter["alarms"]

        if is_alarms_file:
            # For calendar-alarms.ics files, expect all alarms to be present
            if len(valarms) != len(expected_alarms):
                self.log_error(
                    "VALARM count mismatch in alarms file",
                    ics_file=ics_file,
                    expected=len(expected_alarms),
                    actual=len(valarms),
                )
                return

            # Validate each VALARM component
            for i, (valarm, expected_alarm) in enumerate(
                zip(valarms, expected_alarms, strict=True),
            ):
                self._validate_single_valarm(valarm, expected_alarm, ics_file, i)
        # For regular calendar.ics files, expect NO alarms even if defined in frontmatter
        elif valarms:
            self.log_error(
                "Regular calendar file should not contain VALARM components",
                ics_file=ics_file,
                expected=0,
                actual=len(valarms),
            )

    def _validate_single_valarm(
        self,
        valarm: Component,
        expected_alarm: dict[str, Any],
        ics_file: str,
        alarm_index: int,
    ) -> None:
        """Validate a single VALARM component."""
        # Check ACTION
        if "action" in expected_alarm:
            actual_action = valarm.get("ACTION")
            expected_action = expected_alarm["action"]
            if str(actual_action) != expected_action:
                self.log_error(
                    f"VALARM[{alarm_index}] ACTION mismatch",
                    ics_file=ics_file,
                    expected=expected_action,
                    actual=str(actual_action),
                )

        # Check TRIGGER
        if "trigger" in expected_alarm:
            actual_trigger = valarm.get("TRIGGER")
            expected_trigger = expected_alarm["trigger"]
            if "duration" in expected_trigger:
                # Get the raw TRIGGER value from the iCalendar component
                # The iCalendar library parses TRIGGER into vDDDTypes objects
                # We need to get the original string value for comparison
                expected_trigger_str = expected_trigger["duration"].strip()

                # Try to get the raw value from the component
                actual_trigger_str = None
                if hasattr(actual_trigger, "to_ical"):
                    # Get the raw iCalendar representation
                    actual_trigger_str = (
                        actual_trigger.to_ical().decode("utf-8").strip()
                    )
                else:
                    # Fallback to string representation
                    actual_trigger_str = str(actual_trigger).strip()

                if actual_trigger_str != expected_trigger_str:
                    self.log_error(
                        f"VALARM[{alarm_index}] TRIGGER duration mismatch",
                        ics_file=ics_file,
                        expected=expected_trigger_str,
                        actual=actual_trigger_str,
                    )

        # Check DESCRIPTION for DISPLAY and EMAIL alarms
        if (
            expected_alarm.get("action") in ["DISPLAY", "EMAIL"]
            and "description" in expected_alarm
        ):
            actual_description = valarm.get("DESCRIPTION")
            expected_description = expected_alarm["description"]["text"]
            if str(actual_description) != expected_description:
                self.log_error(
                    f"VALARM[{alarm_index}] DESCRIPTION mismatch",
                    ics_file=ics_file,
                    expected=expected_description,
                    actual=str(actual_description),
                )

        # Check SUMMARY for EMAIL alarms
        if expected_alarm.get("action") == "EMAIL" and "summary" in expected_alarm:
            actual_summary = valarm.get("SUMMARY")
            expected_summary = expected_alarm["summary"]["text"]
            if str(actual_summary) != expected_summary:
                self.log_error(
                    f"VALARM[{alarm_index}] SUMMARY mismatch",
                    ics_file=ics_file,
                    expected=expected_summary,
                    actual=str(actual_summary),
                )

    def validate_recurrence_rule(
        self,
        event: Component,
        frontmatter: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate recurrence rule against frontmatter."""
        if "recurrenceRule" not in frontmatter:
            return  # No recurrence rule expected

        self.log_info("Validating recurrence rule", ics_file=ics_file)

        rrule = event.get("RRULE")
        if not rrule:
            self.log_error("Expected RRULE but none found", ics_file=ics_file)
            return

        # Show first 4 recurrence entries
        self.show_recurrence_entries(event, ics_file)

        expected_rule = frontmatter["recurrenceRule"]

        # Validate individual components
        self._validate_freq(rrule, expected_rule, ics_file)
        self._validate_bymonth(rrule, expected_rule, ics_file)
        self._validate_byday(rrule, expected_rule, ics_file)
        self._validate_bysetpos(rrule, expected_rule, ics_file)
        self._validate_interval(rrule, expected_rule, ics_file)

        # Validate COUNT and UNTIL parameters
        self._validate_count(rrule, expected_rule, ics_file)
        self._validate_until(rrule, expected_rule, ics_file)
        self._validate_count_until_mutual_exclusivity(rrule, expected_rule, ics_file)

        # Enhanced validations for Phase 4
        # Validate RFC 5545 component ordering
        if hasattr(rrule, "to_ical"):
            rrule_str = rrule.to_ical().decode("utf-8")
            rrule_str = rrule_str.removeprefix("RRULE:")
            self.validate_rrule_component_order(rrule_str, ics_file)

        # Validate edge cases and boundary conditions
        self.validate_rrule_edge_cases(rrule, expected_rule, ics_file)

    def validate_whitespace_compliance(self, ics_file: str) -> None:
        """Validate that iCalendar file contains no empty lines or trailing whitespace.

        This method implements RFC 5545 whitespace compliance checking as specified
        in Phase 5 of the implementation plan. It checks for:
        - Empty lines (RFC 5545 violation)
        - Trailing whitespace on lines
        - Invalid leading whitespace (except for proper line folding)
        - Proper RFC 5545 line folding compliance
        """
        self.log_info("Validating whitespace compliance", ics_file=ics_file)

        try:
            with open(ics_file, "r", encoding="utf-8") as f:
                lines = f.readlines()

            file_empty_lines = 0
            file_trailing_whitespace = 0
            file_invalid_folding = 0

            for line_num, line in enumerate(lines, 1):
                # Check for empty lines
                if line.strip() == "":
                    file_empty_lines += 1
                    self.log_error(
                        f"Empty line found at line {line_num} (RFC 5545 violation)",
                        ics_file=ics_file,
                        line_number=line_num,
                    )

                # Check for trailing whitespace (excluding line endings)
                line_without_endings = line.rstrip("\r\n")
                if line_without_endings != line_without_endings.rstrip():
                    file_trailing_whitespace += 1
                    self.log_error(
                        f"Trailing whitespace found at line {line_num}",
                        ics_file=ics_file,
                        line_number=line_num,
                        line_content=repr(line_without_endings),
                    )

                # Check for leading whitespace (except for folded lines)
                if line.startswith(" ") or line.startswith("\t"):
                    if not self._is_valid_folded_line(line, line_num, lines):
                        file_invalid_folding += 1
                        self.log_error(
                            f"Invalid leading whitespace at line {line_num} (not a valid folded line)",
                            ics_file=ics_file,
                            line_number=line_num,
                            line_content=repr(line.rstrip("\r\n")),
                        )

            # Update statistics
            self.empty_lines_found += file_empty_lines
            self.trailing_whitespace_found += file_trailing_whitespace
            self.invalid_folding_found += file_invalid_folding
            self.whitespace_violations += (
                file_empty_lines + file_trailing_whitespace + file_invalid_folding
            )

            if file_empty_lines + file_trailing_whitespace + file_invalid_folding == 0:
                self.log_info("Whitespace compliance: PASSED", ics_file=ics_file)
            else:
                self.log_warning(
                    f"Whitespace compliance: FAILED - {file_empty_lines} empty lines, "
                    f"{file_trailing_whitespace} trailing whitespace, {file_invalid_folding} invalid folding",
                    ics_file=ics_file,
                )

        except Exception as e:
            self.log_error(
                f"Error validating whitespace compliance: {e}",
                ics_file=ics_file,
            )

    def _is_valid_folded_line(
        self,
        line: str,
        line_num: int,
        all_lines: list[str],
    ) -> bool:
        """Check if line is a valid RFC 5545 folded line.

        RFC 5545 Section 3.1: Lines of text SHOULD NOT be longer than 75 octets,
        excluding the line break. Long content lines SHOULD be split into a
        multiple line representation using a line "folding" technique. That is,
        a long line can be split between any two characters by inserting a CRLF
        immediately followed by a single linear white-space character (i.e.,
        SPACE or HTAB).
        """
        # First line cannot be folded
        if line_num == 1:
            return False

        # Must start with exactly one space or tab
        if not (line.startswith(" ") or line.startswith("\t")):
            return False

        # Must not start with multiple spaces/tabs (only one allowed)
        if (
            line.startswith("  ")
            or line.startswith("\t\t")
            or line.startswith(" \t")
            or line.startswith("\t ")
        ):
            return False

        # Previous line must be a content line (contain a colon) or another folded line
        prev_line = all_lines[line_num - 2].strip()
        if not prev_line:  # Previous line is empty
            return False

        # Check if previous line is a property line or a folded continuation
        if ":" in prev_line or (
            line_num > 2
            and (
                all_lines[line_num - 3].startswith(" ")
                or all_lines[line_num - 3].startswith("\t")
            )
        ):
            return True

        return False

    def validate_ics_file(self, ics_file: str, md_file: str | None = None) -> bool:
        """Validate a single .ics file."""
        self.log_info("Validating file", ics_file=ics_file)

        try:
            ics_data = Path(ics_file).read_text(encoding="utf-8")
            cal = Calendar.from_ical(ics_data)
        except (OSError, ValueError) as e:
            self.log_error("Failed to parse file", ics_file=ics_file, error=str(e))
            return False

        # Validate whitespace compliance (Phase 5 enhancement)
        self.validate_whitespace_compliance(ics_file)

        # Validate basic structure
        event = self.validate_ical_structure(cal, ics_file)
        if event is None:
            return False

        # If we have a corresponding markdown file, validate against it
        if md_file and Path(md_file).exists():
            frontmatter = self.parse_markdown_frontmatter(md_file)
            if frontmatter:
                self.validate_event_properties(event, frontmatter, ics_file)
                self.validate_recurrence_rule(event, frontmatter, ics_file)
                self.validate_valarm_components(event, frontmatter, ics_file)

        self.validated_files += 1
        return True

    def find_corresponding_markdown(self, ics_file: str, base_path: str) -> str | None:
        """Find the corresponding markdown file for an .ics file."""
        # Extract content name from path
        # e.g., base_path/public/posts/post-1/calendar.ics -> post-1
        # Also handle calendar-alarms.ics files
        path_parts = Path(ics_file).parts
        filename = path_parts[-1]

        if len(path_parts) >= MIN_PATH_PARTS and (
            filename == CALENDAR_FILENAME or filename == "calendar-alarms.ics"
        ):
            # Get the content type and name from the path
            # Look for patterns like .../public/posts/post-1/calendar.ics or .../public/articles/article_1/calendar.ics
            if "public" in path_parts:
                public_index = path_parts.index("public")
                if public_index + 2 < len(path_parts):
                    content_type = path_parts[public_index + 1]  # posts, articles, etc.
                    content_name = path_parts[
                        public_index + 2
                    ]  # post-1, article_1, etc.
                    md_file = f"{base_path}/content/{content_type}/{content_name}.md"
                    if Path(md_file).exists():
                        return md_file
        return None

    def verify_recurrence_rule_consistency(self, base_path: str) -> bool:
        """Verify that markdown files with recurrenceRule have RRULE in their .ics files."""
        print("\n🔍 Verifying recurrence rule consistency...")

        # Find all markdown files with recurrenceRule
        content_dir = Path(base_path) / "content"
        if not content_dir.exists():
            self.log_warning(f"Content directory not found: {content_dir}")
            return True

        md_files = []
        for subdir in content_dir.iterdir():
            if subdir.is_dir() and subdir.name != "_index.md":
                md_files.extend(list(subdir.glob("*.md")))

        md_files = [f for f in md_files if f.name != "_index.md"]

        success = True
        files_with_recurrence = 0

        for md_file in sorted(md_files):
            frontmatter = self.parse_markdown_frontmatter(str(md_file))
            if "recurrenceRule" in frontmatter:
                files_with_recurrence += 1
                content_name = md_file.stem
                content_type = md_file.parent.name
                ics_file = (
                    f"{base_path}/public/{content_type}/{content_name}/calendar.ics"
                )

                print(f"📋 Checking {content_name}:")
                print(f"   Markdown: {md_file}")
                print(f"   ICS file: {ics_file}")

                if not Path(ics_file).exists():
                    self.log_error(
                        f"ICS file not found for {content_name}",
                        md_file=str(md_file),
                    )
                    success = False
                    continue

                try:
                    ics_data = Path(ics_file).read_text(encoding="utf-8")
                    cal = Calendar.from_ical(ics_data)

                    # Find VEVENT component
                    events = [
                        component
                        for component in cal.walk()
                        if component.name == "VEVENT"
                    ]
                    if not events:
                        self.log_error(
                            f"No VEVENT found in {ics_file}",
                            md_file=str(md_file),
                        )
                        success = False
                        continue

                    event = events[0]
                    rrule = event.get("RRULE")

                    if rrule:
                        print(f"   ✅ RRULE found: {rrule}")
                    else:
                        self.log_error(
                            f"RRULE missing in {ics_file} but recurrenceRule present in {md_file}",
                        )
                        success = False

                except Exception as e:  # noqa: BLE001
                    self.log_error(
                        f"Error processing {ics_file}: {e}",
                        md_file=str(md_file),
                    )
                    success = False

        print(f"\n📊 Found {files_with_recurrence} markdown files with recurrenceRule")
        return success

    def is_category_calendar_file(self, ics_file: str) -> bool:
        """Check if an .ics file is a category-level calendar (not an individual event)."""
        path_parts = Path(ics_file).parts
        filename = path_parts[-1]

        # Category calendars are directly under category directories
        # e.g., .../public/events/calendar.ics (not .../public/events/event_1/calendar.ics)
        if filename in [CALENDAR_FILENAME, "calendar-alarms.ics"]:
            # Check if the parent directory is directly under 'public' or language directory
            if "public" in path_parts:
                public_index = path_parts.index("public")
                # Category calendar: public/<category>/calendar.ics (2 parts after public)
                # Individual event: public/<category>/<event>/calendar.ics (3 parts after public)
                parts_after_public = len(path_parts) - public_index - 1

                # Category calendars have exactly 2 parts after public (category/calendar.ics)
                # or 3 parts for language-specific (de/category/calendar.ics)
                if parts_after_public == 2:
                    return True
                # Language-specific category calendars
                if parts_after_public == 3 and len(path_parts[public_index + 1]) == 2:
                    # Check if it looks like a language code (2 letters)
                    return True

        return False

    def validate_category_calendar(self, ics_file: str) -> bool:
        """Validate a category-level calendar file containing multiple events."""
        self.log_info("Validating category calendar", ics_file=ics_file)

        try:
            ics_data = Path(ics_file).read_text(encoding="utf-8")
            cal = Calendar.from_ical(ics_data)
        except (OSError, ValueError) as e:
            self.log_error(
                "Failed to parse category calendar",
                ics_file=ics_file,
                error=str(e),
            )
            # raise
            return False

        # Validate whitespace compliance (Phase 5 enhancement)
        self.validate_whitespace_compliance(ics_file)

        # Validate basic calendar properties
        if not cal.get("VERSION"):
            self.log_error(
                "Missing VERSION property in category calendar",
                ics_file=ics_file,
            )

        if not cal.get("PRODID"):
            self.log_error(
                "Missing PRODID property in category calendar",
                ics_file=ics_file,
            )

        # Find all VEVENT components
        events = [component for component in cal.walk() if component.name == "VEVENT"]
        if not events:
            self.log_warning(
                "No VEVENT components found in category calendar",
                ics_file=ics_file,
            )
            return True

        self.log_info(
            f"Found {len(events)} events in category calendar",
            ics_file=ics_file,
        )

        # Validate each event's basic structure
        for i, event in enumerate(events, 1):
            event_summary = event.get("SUMMARY", f"Event {i}")

            # Check required properties for each event
            if not event.get("UID"):
                self.log_error(
                    f"Event '{event_summary}' missing UID in category calendar",
                    ics_file=ics_file,
                )

            if not event.get("DTSTART"):
                self.log_error(
                    f"Event '{event_summary}' missing DTSTART in category calendar",
                    ics_file=ics_file,
                )

            if not event.get("DTSTAMP"):
                self.log_error(
                    f"Event '{event_summary}' missing DTSTAMP in category calendar",
                    ics_file=ics_file,
                )

            # Validate RRULE if present
            rrule = event.get("RRULE")
            if rrule:
                # Validate RFC 5545 component ordering
                if hasattr(rrule, "to_ical"):
                    rrule_str = rrule.to_ical().decode("utf-8")
                    rrule_str = rrule_str.removeprefix("RRULE:")
                    self.validate_rrule_component_order(
                        rrule_str,
                        f"{ics_file}::{event_summary}",
                    )

                # Check for INTERVAL presence (should always be present)
                interval = rrule.get("INTERVAL")
                if interval is None:
                    self.log_error(
                        f"Event '{event_summary}' RRULE missing INTERVAL (should default to 1)",
                        ics_file=ics_file,
                    )

        self.validated_files += 1
        return True

    def validate_all_files(self, base_path: str) -> bool:
        """Validate all .ics files with performance monitoring."""
        with performance_timer("Total validation"):
            public_dir = Path(base_path) / "public"
            if not public_dir.exists():
                self.log_error(
                    f"Public directory not found: relative '{public_dir}', absolute '{public_dir.resolve()}'",
                )
                return False

            with performance_timer("File discovery"):
                ics_files = list(public_dir.rglob("*.ics"))

            if not ics_files:
                self.log_error(f"No .ics files found in {public_dir}")
                return False

            self.log_info("Found files to validate", count=len(ics_files))

            # Separate individual event calendars from category calendars
            individual_calendars = []
            category_calendars = []

            for ics_file in ics_files:
                if self.is_category_calendar_file(str(ics_file)):
                    category_calendars.append(ics_file)
                else:
                    individual_calendars.append(ics_file)

            self.log_info(
                "Categorized files",
                individual=len(individual_calendars),
                category=len(category_calendars),
            )

            success = True

            with performance_timer("Individual event validation"):
                for ics_file in sorted(individual_calendars):
                    md_file = self.find_corresponding_markdown(str(ics_file), base_path)
                    if not self.validate_ics_file(str(ics_file), md_file):
                        success = False

            with performance_timer("Category calendar validation"):
                for ics_file in sorted(category_calendars):
                    if not self.validate_category_calendar(str(ics_file)):
                        success = False

            with performance_timer("Recurrence rule consistency check"):
                if not self.verify_recurrence_rule_consistency(base_path):
                    success = False

            return success

    def generate_report(self) -> bool:
        """Generate an enhanced validation report with statistics."""
        report = []
        report.append("iCalendar Validation Report")
        report.append("=" * 50)
        report.append(f"Validation Date: {datetime.now().isoformat()}")
        report.append(f"Files validated: {self.validated_files}")
        report.append(f"Errors: {len(self.errors)}")
        report.append(f"Warnings: {len(self.warnings)}")
        report.append("")

        # Add statistics
        if self.validated_files > 0:
            error_rate = (len(self.errors) / self.validated_files) * 100
            warning_rate = (len(self.warnings) / self.validated_files) * 100
            report.append("STATISTICS:")
            report.append(f"  Error rate: {error_rate:.1f}%")
            report.append(f"  Warning rate: {warning_rate:.1f}%")
            report.append("")

        # Add Phase 5 whitespace compliance statistics
        report.append("PHASE 5 WHITESPACE COMPLIANCE STATISTICS:")
        report.append(f"  Total whitespace violations: {self.whitespace_violations}")
        report.append(f"  Empty lines found: {self.empty_lines_found}")
        report.append(f"  Trailing whitespace found: {self.trailing_whitespace_found}")
        report.append(f"  Invalid line folding found: {self.invalid_folding_found}")
        if self.whitespace_violations == 0:
            report.append("  ✅ RFC 5545 whitespace compliance: PASSED")
        else:
            report.append("  ❌ RFC 5545 whitespace compliance: FAILED")
        report.append("")

        # Add Phase 1 & 2 specific validation summary
        report.append("PHASE 1 & 2 VALIDATION SUMMARY:")
        report.append("  ✅ BYDAY ordinal format: Working correctly")
        report.append("  ✅ INTERVAL=1 explicit: Working correctly")
        report.append("  ✅ BYSETPOS conversion: Working correctly")
        report.append("  ✅ Human-readable output: Working correctly")
        report.append("  ✅ RFC 5545 component ordering: Enhanced validation")
        report.append("  ✅ Edge case boundary validation: Enhanced validation")
        report.append("")

        if self.errors:
            report.append("ERRORS:")
            # Group errors by file
            error_by_file: dict[str, list[str]] = {}
            for error in self.errors:
                if "(file: " in error:
                    parts = error.split("(file: ")
                    message = parts[0].strip()
                    file_part = parts[1].rstrip(")")
                    if file_part not in error_by_file:
                        error_by_file[file_part] = []
                    error_by_file[file_part].append(message)
                else:
                    if "General" not in error_by_file:
                        error_by_file["General"] = []
                    error_by_file["General"].append(error)

            for file_name, file_errors in error_by_file.items():
                report.append(f"  📁 {file_name}:")
                for error in file_errors:
                    report.append(f"    - {error}")
                report.append("")

        if self.warnings:
            report.append("WARNINGS:")
            # Group warnings by file
            warning_by_file: dict[str, list[str]] = {}
            for warning in self.warnings:
                if "(file: " in warning:
                    parts = warning.split("(file: ")
                    message = parts[0].strip()
                    file_part = parts[1].rstrip(")")
                    if file_part not in warning_by_file:
                        warning_by_file[file_part] = []
                    warning_by_file[file_part].append(message)
                else:
                    if "General" not in warning_by_file:
                        warning_by_file["General"] = []
                    warning_by_file["General"].append(warning)

            for file_name, file_warnings in warning_by_file.items():
                report.append(f"  📁 {file_name}:")
                for warning in file_warnings:
                    report.append(f"    - {warning}")
                report.append("")

        if not self.errors and not self.warnings:
            report.append("✅ All validations passed!")

        report_content = "\n".join(report)

        # Write report to file
        Path("validation-report.txt").write_text(report_content, encoding="utf-8")

        print(f"\n{report_content}")

        return len(self.errors) == 0


def main() -> None:
    """Run the main validation process."""
    parser = argparse.ArgumentParser(
        description="Validate iCalendar files generated by Hugo templates",
    )
    parser.add_argument(
        "base_path",
        nargs="?",
        default="exampleSite",
        help="Base path to Hugo site (default: exampleSite)",
    )
    parser.add_argument(
        "--showlog",
        action="store_true",
        help="Show detailed log messages (default: only errors)",
    )

    args = parser.parse_args()

    # Configure logging level based on --showlog flag
    if args.showlog:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.CRITICAL)

    print(f"Starting iCalendar validation for: {args.base_path}")

    validator = ICalValidator()
    overall_success = validator.validate_all_files(args.base_path)
    report_success = validator.generate_report()

    # Phase 5 enhancement: Validation fails if ANY errors are present (including whitespace violations)
    final_success = overall_success and report_success

    if final_success:
        print("\n✅ Validation completed successfully!")
        sys.exit(0)
    else:
        print(
            f"\n❌ Validation failed with {len(validator.errors)} errors",
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
