#!/usr/bin/env python3
"""iCalendar Validation Script for Hugo iCalendar Templates.

This script validates the generated .ics files to ensure they:
1. Are valid iCalendar format using the icalendar library
2. Contain expected properties
3. Have correct recurrence rules
4. Match the source markdown content when comparison is needed

Usage:
    python validate_ics.py <base_path>

Where <base_path> is the root directory containing the Hugo site structure.
For theme component: hugo-theme-component-ical/.github/exampleSite
For demo site: demo
"""

import argparse
from collections.abc import Generator
import sys
import time
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml
from dateutil.rrule import rrulestr
from icalendar import Calendar, Component

# Constants
MIN_PATH_PARTS = 2
CALENDAR_FILENAME = "calendar.ics"


@contextmanager
def performance_timer(operation_name: str) -> Generator[None, Any, None]:
    """Context manager for timing operations."""
    start_time = time.time()
    try:
        yield
    finally:
        end_time = time.time()
        duration = end_time - start_time
        print(f"⏱️  {operation_name}: {duration:.3f}s")


class ICalValidator:
    """Validator for iCalendar files generated by Hugo templates."""

    def __init__(self) -> None:
        """Initialize the validator with empty error and warning lists."""
        self.errors: list[str] = []
        self.warnings: list[str] = []
        self.validated_files: int = 0

    def log_error(self, message: str, **kwargs: Any) -> None:
        """Log an error message."""
        # Include file name in the error message if available
        ics_file = kwargs.get("ics_file", "")
        formatted_message = f"{message} (file: {ics_file})" if ics_file else message
        self.errors.append(formatted_message)
        print(f"ERROR: {message}")

    def log_warning(self, message: str, **kwargs: Any) -> None:
        """Log a warning message."""
        # Include file name in the warning message if available
        ics_file = kwargs.get("ics_file", "")
        formatted_message = f"{message} (file: {ics_file})" if ics_file else message
        self.warnings.append(formatted_message)
        print(f"WARNING: {message}")

    def log_info(self, message: str, **kwargs: Any) -> None:
        """Log an info message."""
        if kwargs.get("verbose", False):
            print(f"INFO: {message}")

    def parse_markdown_frontmatter(self, md_file: str) -> dict[str, Any]:
        """Parse the YAML frontmatter from a markdown file."""
        try:
            content = Path(md_file).read_text(encoding="utf-8")

            # Extract frontmatter between --- markers
            if content.startswith("---\n"):
                end_marker = content.find("\n---\n", 4)
                if end_marker != -1:
                    frontmatter = content[4:end_marker]
                    return yaml.safe_load(frontmatter) or {}
            else:
                return {}
        except (OSError, yaml.YAMLError) as e:
            self.log_error(
                "Failed to parse frontmatter from file",
                md_file=md_file,
                error=str(e),
            )
        return {}

    def validate_ical_structure(
        self,
        cal: Component,
        ics_file: str,
    ) -> Component | None:
        """Validate basic iCalendar structure."""
        self.log_info("Validating structure", ics_file=ics_file)

        # Check for required calendar properties
        if not cal.get("VERSION"):
            self.log_error("Missing VERSION property", ics_file=ics_file)

        if not cal.get("PRODID"):
            self.log_error("Missing PRODID property", ics_file=ics_file)

        # Check for events
        events = [component for component in cal.walk() if component.name == "VEVENT"]
        if not events:
            self.log_error("No VEVENT components found", ics_file=ics_file)
            return None

        return events[0]  # Return first event for further validation

    def validate_event_properties(
        self,
        event: Component,
        frontmatter: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate event properties against frontmatter."""
        self.log_info("Validating event properties", ics_file=ics_file)

        # Check SUMMARY (title)
        if "title" in frontmatter:
            summary = event.get("SUMMARY")
            if summary:
                if str(summary) != frontmatter["title"]:
                    self.log_error(
                        "SUMMARY doesn't match title",
                        ics_file=ics_file,
                        summary=str(summary),
                        expected_title=frontmatter["title"],
                    )
            else:
                self.log_error("Missing SUMMARY property", ics_file=ics_file)

        # Check DTSTART
        if "startDate" in frontmatter:
            dtstart = event.get("DTSTART")
            if not dtstart:
                self.log_error("Missing DTSTART property", ics_file=ics_file)
            else:
                # Validate UTC format (should have Z suffix)
                self.validate_utc_datetime(dtstart, "DTSTART", ics_file)

        # Check DTEND - be more flexible about detection
        if "endDate" in frontmatter:
            dtend = event.get("DTEND")
            if not dtend:
                # Try to detect DTEND in raw ical data if icalendar library failed to parse it
                # This can happen when there are formatting issues in the .ics file
                raw_content = Path(ics_file).read_text(encoding="utf-8")
                if "DTEND" in raw_content:
                    self.log_warning(
                        "DTEND property found in file but not parsed correctly (possible formatting issue)",
                        ics_file=ics_file,
                    )
                else:
                    self.log_error("Missing DTEND property", ics_file=ics_file)
            else:
                # Validate UTC format (should have Z suffix)
                self.validate_utc_datetime(dtend, "DTEND", ics_file)

        # Check UID
        uid = event.get("UID")
        if not uid:
            self.log_error("Missing UID property", ics_file=ics_file)

        # Check DTSTAMP
        dtstamp = event.get("DTSTAMP")
        if not dtstamp:
            self.log_error("Missing DTSTAMP property", ics_file=ics_file)
        else:
            # Validate UTC format (should have Z suffix)
            self.validate_utc_datetime(dtstamp, "DTSTAMP", ics_file)

    def validate_utc_datetime(
        self, dt_property: Any, property_name: str, ics_file: str
    ) -> None:
        """Validate that a datetime property is in UTC format (ends with Z)."""
        try:
            # Get the actual datetime value
            dt_value = dt_property.dt if hasattr(dt_property, "dt") else dt_property

            # Check if it's a datetime with UTC timezone
            if hasattr(dt_value, "tzinfo") and dt_value.tzinfo is not None:
                # Handle both pytz and zoneinfo UTC representations
                timezone_str = str(dt_value.tzinfo)
                is_utc = (
                    timezone_str == "UTC"
                    or timezone_str == "+00:00"
                    or timezone_str == "utc"
                    or getattr(dt_value.tzinfo, "key", None) == "UTC"
                    or getattr(dt_value.tzinfo, "zone", None) == "UTC"
                )

                if not is_utc:
                    self.log_warning(
                        f"{property_name} should be in UTC format but has timezone: {dt_value.tzinfo}",
                        ics_file=ics_file,
                    )

            # Check the raw iCalendar representation for Z suffix
            if hasattr(dt_property, "to_ical"):
                ical_str = dt_property.to_ical().decode("utf-8")
                if not ical_str.endswith("Z"):
                    self.log_warning(
                        f"{property_name} should end with 'Z' for UTC format, got: {ical_str}",
                        ics_file=ics_file,
                    )
        except Exception as e:
            # Only log warning if it's not the known zoneinfo issue
            if "'zoneinfo.ZoneInfo' object has no attribute 'zone'" not in str(e):
                self.log_warning(
                    f"Could not validate UTC format for {property_name}: {e}",
                    ics_file=ics_file,
                )

    def validate_recurrence_rule(
        self,
        event: Component,
        frontmatter: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate recurrence rule against frontmatter."""
        if "recurrenceRule" not in frontmatter:
            return  # No recurrence rule expected

        self.log_info("Validating recurrence rule", ics_file=ics_file)

        rrule = event.get("RRULE")
        if not rrule:
            self.log_error("Expected RRULE but none found", ics_file=ics_file)
            return

        # Show first 4 recurrence entries
        self.show_recurrence_entries(event, ics_file)

        expected_rule = frontmatter["recurrenceRule"]

        # Validate FREQ parameter
        if "freq" in expected_rule:
            actual_freq = rrule.get("FREQ")
            expected_freq = [expected_rule["freq"]]
            if actual_freq != expected_freq:
                self.log_error(
                    "FREQ mismatch",
                    ics_file=ics_file,
                    expected=expected_rule["freq"],
                    actual=actual_freq,
                )

        # Validate INTERVAL parameter - should always be present
        expected_interval_value = expected_rule.get("interval", 1)
        expected_interval = [expected_interval_value]
        actual_interval = rrule.get("INTERVAL")
        if actual_interval != expected_interval:
            self.log_error(
                "INTERVAL mismatch (INTERVAL is now always required)",
                ics_file=ics_file,
                expected=expected_interval,
                actual=actual_interval,
            )

        # Validate COUNT parameter if present
        if "count" in expected_rule:
            expected_count = [expected_rule["count"]]
            actual_count = rrule.get("COUNT")
            if actual_count != expected_count:
                self.log_error(
                    "COUNT mismatch",
                    ics_file=ics_file,
                    expected=expected_count,
                    actual=actual_count,
                )
            else:
                print(
                    f"ℹ️  Event will occur {expected_rule['count']} times (COUNT={expected_rule['count']})"
                )

        # Validate UNTIL parameter if present
        if "until" in expected_rule:
            actual_until = rrule.get("UNTIL")
            if actual_until is None:
                self.log_error(
                    "UNTIL missing",
                    ics_file=ics_file,
                    expected=expected_rule["until"],
                    actual=None,
                )
            else:
                # Just verify that UNTIL exists and is valid
                actual_until_dt = (
                    actual_until[0] if isinstance(actual_until, list) else actual_until
                )
                if hasattr(actual_until_dt, "strftime"):
                    readable_date = actual_until_dt.strftime("%Y-%m-%d")
                    print(f"ℹ️  Event will occur until {readable_date} (UNTIL found)")
                else:
                    print(f"ℹ️  Event has UNTIL parameter: {actual_until_dt}")

        # Validate BYDAY parameter
        if "byDay" in expected_rule:
            expected_day = expected_rule["byDay"]
            expected_setpos = expected_rule.get("bySetPos")

            # Normalize to list for comparison
            if not isinstance(expected_day, list):
                expected_day = [expected_day]

            actual_day = rrule.get("BYDAY")

            # Check if we should expect ordinal BYDAY format (BYDAY+BYSETPOS conversion)
            if expected_setpos is not None and len(expected_day) == 1:
                # Single day with setpos should be converted to ordinal format
                if not isinstance(expected_setpos, list):
                    expected_setpos = [expected_setpos]

                if len(expected_setpos) == 1:
                    # Should be converted to ordinal format like "3TH"
                    expected_ordinal = [f"{expected_setpos[0]}{expected_day[0]}"]
                    if actual_day != expected_ordinal:
                        self.log_error(
                            "BYDAY ordinal format mismatch (converted from BYDAY+BYSETPOS)",
                            ics_file=ics_file,
                            expected=expected_ordinal,
                            actual=actual_day,
                            original_byday=expected_day,
                            original_bysetpos=expected_setpos,
                        )
                    return

            # Standard BYDAY validation (no conversion)
            if actual_day != expected_day:
                self.log_error(
                    "BYDAY mismatch",
                    ics_file=ics_file,
                    expected=expected_day,
                    actual=actual_day,
                )

        # Validate BYSETPOS parameter
        if "bySetPos" in expected_rule:
            expected_setpos = expected_rule["bySetPos"]
            expected_day = expected_rule.get("byDay")

            if isinstance(expected_setpos, list):
                expected_setpos_list = expected_setpos
            else:
                expected_setpos_list = [expected_setpos]

            actual_setpos = rrule.get("BYSETPOS")

            # Check if BYSETPOS should be converted to ordinal BYDAY format
            if expected_day is not None:
                # Normalize expected_day to list
                if not isinstance(expected_day, list):
                    expected_day = [expected_day]

                # If single day and single setpos, should be converted to ordinal format
                if len(expected_day) == 1 and len(expected_setpos_list) == 1:
                    # BYSETPOS should be absent (converted to ordinal BYDAY)
                    if actual_setpos is not None:
                        self.log_error(
                            "BYSETPOS should be absent (converted to ordinal BYDAY format)",
                            ics_file=ics_file,
                            expected=None,
                            actual=actual_setpos,
                            converted_to_ordinal=f"{expected_setpos_list[0]}{expected_day[0]}",
                        )
                    return

            # Standard BYSETPOS validation (no conversion)
            if actual_setpos != expected_setpos_list:
                self.log_error(
                    "BYSETPOS mismatch",
                    ics_file=ics_file,
                    expected=expected_setpos_list,
                    actual=actual_setpos,
                )

        # Validate BYMONTH parameter
        if "byMonth" in expected_rule:
            expected_month = [expected_rule["byMonth"]]
            actual_month = rrule.get("BYMONTH")
            if actual_month != expected_month:
                self.log_error(
                    "BYMONTH mismatch",
                    ics_file=ics_file,
                    expected=expected_month,
                    actual=actual_month,
                )

        # Validate COUNT and UNTIL mutual exclusivity
        has_count = "count" in expected_rule
        has_until = "until" in expected_rule

        if has_count and has_until:
            self.log_warning(
                "COUNT and UNTIL both present in frontmatter (RFC 5545 violation - they are mutually exclusive)",
                ics_file=ics_file,
            )

        actual_count = rrule.get("COUNT")
        actual_until = rrule.get("UNTIL")

        if actual_count is not None and actual_until is not None:
            self.log_error(
                "COUNT and UNTIL both present in RRULE (RFC 5545 violation - they are mutually exclusive)",
                ics_file=ics_file,
                count=actual_count,
                until=actual_until,
            )

    def show_recurrence_entries(self, event: Component, ics_file: str) -> None:
        """Show the first 4 entries from recurrence rules."""
        rrule = event.get("RRULE")
        if not rrule:
            return

        dtstart = event.get("DTSTART")
        if not dtstart:
            return

        try:
            # Get RRULE string from the iCalendar component
            if hasattr(rrule, "to_ical"):
                rrule_str = rrule.to_ical().decode("utf-8")
                rrule_str = rrule_str.removeprefix("RRULE:")
            else:
                rrule_str = str(rrule)
                rrule_str = rrule_str.removeprefix("RRULE:")

            start_dt = dtstart.dt

            # Handle UTC timezone - convert Z suffix dates to naive datetime for rrulestr
            if hasattr(start_dt, "tzinfo") and start_dt.tzinfo is not None:
                # For UTC dates (ending with Z), convert to naive datetime
                start_dt = start_dt.replace(tzinfo=None)

            # Generate first 4 occurrences
            try:
                rule = rrulestr(rrule_str, dtstart=start_dt)
                occurrences = []
                for i, occurrence in enumerate(rule):
                    if i >= 4:
                        break
                    occurrences.append(occurrence)

                print(f"\n📅 First 4 recurrence entries for {ics_file}:")
                for i, occurrence in enumerate(occurrences, 1):
                    print(f"  {i}. {occurrence.strftime('%Y-%m-%d %H:%M:%S')}")
            except ValueError as ve:
                # Don't warn for UTC UNTIL parsing issues - this is expected with UTC format
                if (
                    "RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware"
                    not in str(ve)
                ):
                    self.log_warning(
                        f"RRULE parsing failed: {ve}. RRULE: {rrule_str}",
                        ics_file=ics_file,
                    )
            except Exception as e:
                self.log_warning(
                    f"Could not generate recurrence entries: {e}",
                    ics_file=ics_file,
                )

        except Exception as e:
            self.log_warning(
                f"Error processing recurrence rule: {e}",
                ics_file=ics_file,
            )

    def validate_valarm_components(
        self,
        event: Component,
        frontmatter: dict[str, Any],
        ics_file: str,
    ) -> None:
        """Validate VALARM components against frontmatter."""
        # Determine if this is a calendar-alarms.ics file or regular calendar.ics
        is_alarms_file = "calendar-alarms.ics" in ics_file

        # Find VALARM components
        valarms = [
            component for component in event.walk() if component.name == "VALARM"
        ]

        if "alarms" not in frontmatter:
            # No alarms defined in frontmatter
            if valarms:
                self.log_error(
                    "Unexpected VALARM components found",
                    ics_file=ics_file,
                    actual=len(valarms),
                )
            return

        self.log_info("Validating VALARM components", ics_file=ics_file)
        expected_alarms = frontmatter["alarms"]

        if is_alarms_file:
            # For calendar-alarms.ics files, expect all alarms to be present
            if len(valarms) != len(expected_alarms):
                self.log_error(
                    "VALARM count mismatch in alarms file",
                    ics_file=ics_file,
                    expected=len(expected_alarms),
                    actual=len(valarms),
                )
                return

            # Validate each VALARM component
            for i, (valarm, expected_alarm) in enumerate(
                zip(valarms, expected_alarms, strict=True),
            ):
                # Check ACTION
                if "action" in expected_alarm:
                    actual_action = valarm.get("ACTION")
                    expected_action = expected_alarm["action"]
                    if str(actual_action) != expected_action:
                        self.log_error(
                            f"VALARM[{i}] ACTION mismatch",
                            ics_file=ics_file,
                            expected=expected_action,
                            actual=str(actual_action),
                        )

                # Check basic VALARM structure
                if not valarm.get("TRIGGER"):
                    self.log_error(
                        f"VALARM[{i}] missing TRIGGER",
                        ics_file=ics_file,
                    )

        # For regular calendar.ics files, expect NO alarms even if defined in frontmatter
        elif valarms:
            self.log_error(
                "Regular calendar file should not contain VALARM components",
                ics_file=ics_file,
                expected=0,
                actual=len(valarms),
            )

    def validate_ics_file(self, ics_file: str, md_file: str | None = None) -> bool:
        """Validate a single .ics file."""
        self.log_info("Validating file", ics_file=ics_file)

        try:
            # Use only the icalendar library to parse the file
            ics_data = Path(ics_file).read_text(encoding="utf-8")
            cal = Calendar.from_ical(ics_data)
        except (OSError, ValueError) as e:
            self.log_error("Failed to parse file", ics_file=ics_file, error=str(e))
            return False

        # Validate basic structure
        event = self.validate_ical_structure(cal, ics_file)
        if event is None:
            return False

        # If we have a corresponding markdown file, validate against it
        if md_file and Path(md_file).exists():
            frontmatter = self.parse_markdown_frontmatter(md_file)
            if frontmatter:
                self.validate_event_properties(event, frontmatter, ics_file)
                self.validate_recurrence_rule(event, frontmatter, ics_file)
                self.validate_valarm_components(event, frontmatter, ics_file)

        self.validated_files += 1
        return True

    def find_corresponding_markdown(self, ics_file: str, base_path: str) -> str | None:
        """Find the corresponding markdown file for an .ics file."""
        # Extract content name from path
        path_parts = Path(ics_file).parts
        filename = path_parts[-1]

        if len(path_parts) >= MIN_PATH_PARTS and (
            filename == CALENDAR_FILENAME or filename == "calendar-alarms.ics"
        ):
            # Get the content type and name from the path
            if "public" in path_parts:
                public_index = path_parts.index("public")
                if public_index + 2 < len(path_parts):
                    content_type = path_parts[public_index + 1]  # posts, articles, etc.
                    content_name = path_parts[
                        public_index + 2
                    ]  # post-1, article_1, etc.
                    md_file = f"{base_path}/content/{content_type}/{content_name}.md"
                    if Path(md_file).exists():
                        return md_file
        return None

    def is_category_calendar_file(self, ics_file: str) -> bool:
        """Check if an .ics file is a category-level calendar (not an individual event)."""
        path_parts = Path(ics_file).parts
        filename = path_parts[-1]

        if filename in [CALENDAR_FILENAME, "calendar-alarms.ics"]:
            if "public" in path_parts:
                public_index = path_parts.index("public")
                parts_after_public = len(path_parts) - public_index - 1

                # Category calendars have exactly 2 parts after public (category/calendar.ics)
                # or 3 parts for language-specific (de/category/calendar.ics)
                if parts_after_public == 2:
                    return True
                if parts_after_public == 3 and len(path_parts[public_index + 1]) == 2:
                    return True

        return False

    def validate_category_calendar(self, ics_file: str) -> bool:
        """Validate a category-level calendar file containing multiple events."""
        self.log_info("Validating category calendar", ics_file=ics_file)

        try:
            # Use only the icalendar library to parse the file
            ics_data = Path(ics_file).read_text(encoding="utf-8")
            cal = Calendar.from_ical(ics_data)
        except (OSError, ValueError) as e:
            self.log_error(
                "Failed to parse category calendar",
                ics_file=ics_file,
                error=str(e),
            )
            return False

        # Validate basic calendar properties
        if not cal.get("VERSION"):
            self.log_error(
                "Missing VERSION property in category calendar",
                ics_file=ics_file,
            )

        if not cal.get("PRODID"):
            self.log_error(
                "Missing PRODID property in category calendar",
                ics_file=ics_file,
            )

        # Find all VEVENT components
        events = [component for component in cal.walk() if component.name == "VEVENT"]
        if not events:
            self.log_warning(
                "No VEVENT components found in category calendar",
                ics_file=ics_file,
            )
            return True

        self.log_info(
            f"Found {len(events)} events in category calendar",
            ics_file=ics_file,
        )

        # Validate each event's basic structure
        for i, event in enumerate(events, 1):
            event_summary = event.get("SUMMARY", f"Event {i}")

            # Check required properties for each event
            if not event.get("UID"):
                self.log_error(
                    f"Event '{event_summary}' missing UID in category calendar",
                    ics_file=ics_file,
                )

            if not event.get("DTSTART"):
                self.log_error(
                    f"Event '{event_summary}' missing DTSTART in category calendar",
                    ics_file=ics_file,
                )

            if not event.get("DTSTAMP"):
                self.log_error(
                    f"Event '{event_summary}' missing DTSTAMP in category calendar",
                    ics_file=ics_file,
                )

            # Check for INTERVAL presence in RRULE if present
            rrule = event.get("RRULE")
            if rrule:
                interval = rrule.get("INTERVAL")
                if interval is None:
                    self.log_error(
                        f"Event '{event_summary}' RRULE missing INTERVAL (should default to 1)",
                        ics_file=ics_file,
                    )

        self.validated_files += 1
        return True

    def validate_all_files(self, base_path: str) -> bool:
        """Validate all .ics files with performance monitoring."""
        with performance_timer("Total validation"):
            public_dir = Path(base_path) / "public"
            if not public_dir.exists():
                self.log_error(
                    f"Public directory not found: relative '{public_dir}', absolute '{public_dir.resolve()}'",
                )
                return False

            with performance_timer("File discovery"):
                ics_files = list(public_dir.rglob("*.ics"))

            if not ics_files:
                self.log_error(f"No .ics files found in {public_dir}")
                return False

            self.log_info("Found files to validate", count=len(ics_files))

            # Separate individual event calendars from category calendars
            individual_calendars = []
            category_calendars = []

            for ics_file in ics_files:
                if self.is_category_calendar_file(str(ics_file)):
                    category_calendars.append(ics_file)
                else:
                    individual_calendars.append(ics_file)

            self.log_info(
                "Categorized files",
                individual=len(individual_calendars),
                category=len(category_calendars),
            )

            success = True

            with performance_timer("Individual event validation"):
                for ics_file in sorted(individual_calendars):
                    md_file = self.find_corresponding_markdown(str(ics_file), base_path)
                    if not self.validate_ics_file(str(ics_file), md_file):
                        success = False

            with performance_timer("Category calendar validation"):
                for ics_file in sorted(category_calendars):
                    if not self.validate_category_calendar(str(ics_file)):
                        success = False

            return success

    def generate_report(self) -> bool:
        """Generate a validation report."""
        report = []
        report.append("iCalendar Validation Report")
        report.append("=" * 50)
        report.append(f"Validation Date: {datetime.now().isoformat()}")
        report.append(f"Files validated: {self.validated_files}")
        report.append(f"Errors: {len(self.errors)}")
        report.append(f"Warnings: {len(self.warnings)}")
        report.append("")

        if self.errors:
            report.append("ERRORS:")
            # Group errors by file
            error_by_file: dict[str, list[str]] = {}
            for error in self.errors:
                if "(file: " in error:
                    parts = error.split("(file: ")
                    message = parts[0].strip()
                    file_part = parts[1].rstrip(")")
                    if file_part not in error_by_file:
                        error_by_file[file_part] = []
                    error_by_file[file_part].append(message)
                else:
                    if "General" not in error_by_file:
                        error_by_file["General"] = []
                    error_by_file["General"].append(error)

            for file_name, file_errors in error_by_file.items():
                report.append(f"  📁 {file_name}:")
                for error in file_errors:
                    report.append(f"    - {error}")
                report.append("")

        if self.warnings:
            report.append("WARNINGS:")
            # Group warnings by file
            warning_by_file: dict[str, list[str]] = {}
            for warning in self.warnings:
                if "(file: " in warning:
                    parts = warning.split("(file: ")
                    message = parts[0].strip()
                    file_part = parts[1].rstrip(")")
                    if file_part not in warning_by_file:
                        warning_by_file[file_part] = []
                    warning_by_file[file_part].append(message)
                else:
                    if "General" not in warning_by_file:
                        warning_by_file["General"] = []
                    warning_by_file["General"].append(warning)

            for file_name, file_warnings in warning_by_file.items():
                report.append(f"  📁 {file_name}:")
                for warning in file_warnings:
                    report.append(f"    - {warning}")
                report.append("")

        report_content = "\n".join(report)

        # Write to file
        try:
            with open("validation-report.txt", "w", encoding="utf-8") as f:
                f.write(report_content)
        except OSError as e:
            print(f"Failed to write validation report: {e}")
            return False

        # Print summary
        if self.errors:
            print(
                f"\n❌ Validation failed with {len(self.errors)} errors and {len(self.warnings)} warnings"
            )
            return False
        elif self.warnings:
            print(f"\n⚠️ Validation passed with {len(self.warnings)} warnings")
            return True
        else:
            print(
                f"\n✅ Validation passed successfully! ({self.validated_files} files validated)"
            )
            return True


def main() -> None:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Validate iCalendar files generated by Hugo templates",
    )
    parser.add_argument(
        "base_path",
        help="Base path containing the Hugo site structure",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    validator = ICalValidator()

    print("🔍 Starting iCalendar validation...")
    print(f"📂 Base path: {args.base_path}")

    overall_success = validator.validate_all_files(args.base_path)

    print("\n📊 Generating validation report...")
    report_success = validator.generate_report()

    if overall_success and report_success:
        print("✅ All validations passed successfully!")
        sys.exit(0)
    else:
        print("❌ Validation failed. Check validation-report.txt for details.")
        sys.exit(1)


if __name__ == "__main__":
    main()
