baseURL = 'https://finkregh.github.io/hugo-theme-component-ical/'
languageCode = 'en-us'
title = 'Demo of hugo-theme-component-ical'

[module]
# replacement pointing to local folder, required to get _this_ variant in the CI
# not required otherwise
replacements = 'github.com/finkregh/hugo-theme-component-ical -> ../../..'

# This theme component
[[module.imports]]
path = 'github.com/finkregh/hugo-theme-component-ical'

# The base theme for the demo site
[[module.imports]]
path = 'golang.foundata.com/hugo-theme-dev'

[params]
[params.feature]
debug = true # default: false

# Define calendar output via cascading front matter for event pages only
[outputs]
page = ["HTML", "Calendar", "CalendarWithAlarms"]
section = ["HTML", "Calendar", "CalendarWithAlarms"]

[outputFormats.Calendar]
baseName = "calendar"
mediaType = "text/calendar"
isPlainText = true
permalinkable = true
suffix = "ics"
# Avoid webcal scheme
protocol = "https://"

[outputFormats.CalendarWithAlarms]
baseName = "calendar-alarms"
mediaType = "text/calendar"
isPlainText = true
permalinkable = true
suffix = "ics"
# Avoid webcal scheme
protocol = "https://"
