name: Semver Release

on:
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install cocogitto
        uses: cocogitto/cocogitto-action@v4
        with:
          install-only: true
      - name: Semver release
        id: cog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cog bump --auto --skip-ci
          VERSION="$(git describe --tags "$(git rev-list --tags --max-count=1)")"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Generate changelog
        id: changelog
        run: |
          CHANGELOG="$(cog changelog --at "${{ steps.cog.outputs.version }}" 2>/dev/null)"
          {
            echo "body<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          body: ${{ steps.changelog.outputs.body }}
          tag_name: ${{ steps.cog.outputs.version }}
