name: Semver Release

on:
  workflow_dispatch:
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Semver release
        id: cog
        uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto --skip-ci
      - name: Generate changelog
        id: changelog
        uses: cocogitto/cocogitto-action@v4
        with:
          command: changelog
          args: --at ${{ steps.cog.outputs.version }}
      - name: Release
        uses: softprops/action-gh-release@v3.0.0
        with:
          body: ${{ steps.changelog.outputs.stdout }}
          tag_name: ${{ steps.cog.outputs.version }}
